//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScheduleClass()
        {
            this.Enrollments = new HashSet<Enrollment>();
        }
    
        public int ScheduleClassesID { get; set; }
        public int CourseID { get; set; }
        public Nullable<System.DateTime> StarteDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string InstructorName { get; set; }
        public int SCSID { get; set; }
        public string Location { get; set; }
    
        public virtual Cours Cours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        public virtual ScheduledClassStatus ScheduledClassStatus { get; set; }
    }
}
